language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
install:
  - "pip install setuptools --upgrade"
  - "pip install pytest"
  - "pip install ."
env:
  - MODEL_TECH=dummy_value
script:
  - "fusesoc init -y"
  - "fusesoc list-cores"
  - "fusesoc library update"
  - "pytest"
